version: "3.8"
services:
  magiclinksdev:
    image: "micahparks/magiclinksdevnop"
    ports:
      - "8080:8080"
    volumes:
      - "./config.quickstart.json:/config.json"
  mldpostgres:
    image: "postgres:15"
    environment:
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    volumes:
      - "./storage/postgres/startup.sql:/docker-entrypoint-initdb.d/startup.sql"
